[package]
name = "assessment-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
week7 = { path = "../week7" }
petgraph = "0.6"
week8 = { path = "../week8" }
week9 = { path = "../week9" }
